#!/bin/sh
#
#  uf-bare - Extract the bare sequence data from an unfasta stream.
#  Copyright (C) 2016  Marco van Zwetselaar <io@zwets.it>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  This utility is part of http://io.zwets.it/unfasta

# Function to exit this script with an error message on stderr
err_exit() {
    echo "$(basename "$0"): $*" >&2
    exit 1
}

# Function to show usage information and exit
usage_exit() {
    echo "
Usage: $(basename $0) [OPTIONS] [FILE ...]

  Output only the bare sequences from each FILE to standard output, dropping the
  headers.  If no FILE is present or FILE is '-', read from standard input.

  Options
   -w HDRSFILE   Write the headers to HDRSFILE, which must not already exist.
   -f|--force    Overwrite HDRSFILE if it exists.

  By default headers go to /dev/null.  Use option -w to store them in a file.
  The file can be merged back in with bare sequences using 'uf-dress'.
" >&2
    exit ${1:-1}
}

# Parse options

unset HDRSFILE FORCE

while [ $# -ne 0 -a "$(expr "$1" : '\(.\)..*')" = "-" ]; do
    case $1 in
    -w)    shift
        [ $# -ge 1 ] || usage_exit
        HDRSFILE="$1"
        ;;
    -f|--force)
        FORCE="yes"
        ;;
    --help)
        usage_exit 0
        ;;
    *) usage_exit
        ;;
    esac
    shift
done

# Check options validity

[ -z "$HDRSFILE" ] || [ -n "$FORCE" ] || [ ! -e "$HDRSFILE" ] || err_exit "file exists (use --force to overwrite): '$HDRSFILE'"

# Do the work

awk -b -O -v F="$HDRSFILE" '
    NR%2==1 && F { print > F }
    NR%2==0' "$@"

# vim: sts=4:sw=4:et:si:ai
